# -*- coding: utf-8 -*-
"""Simple_recommender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1spchxaYgtCFjJKL-4xFkPJkRFzHZlLrg
"""

import pandas as pd
import numpy as np

data = pd.read_csv('/content/movies_metadata.csv')

data.shape

data.head()

vote_count = data['vote_count']
vote_average = data['vote_average']
mean_of_avg = vote_average.mean()

threshold_value = vote_count.quantile(0.90)

threshold_value

data_copy = data.copy().loc[data['vote_count'] >= threshold_value]

data_copy.shape

def score(dataframe,t = threshold_value,m = mean_of_avg):
  vf = dataframe['vote_count']
  va = dataframe['vote_average']
  wa = (vf/(vf+t)*va) + (t/(t+vf)*m)
  return wa

data_copy['score'] = data_copy.apply(score,axis=1)

data_copy.head()

data_copy = data_copy.sort_values('score',ascending =False)

data_copy.head(10)

